dew:
  basic:
    name: Dew服务框架
    version: 1.0
    desc:
    webSite: www.ecfront.com
    doc:
      basePackage: "com.ecfront"
    entity:
      basePackages: [""]

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 24000
eureka:
  instance:
    metadata-map:
      cluster: dew
